# Generated by Django 6.0.2 on 2026-02-18 09:27

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='LoanApplication',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('applicant_id', models.CharField(blank=True, max_length=20, unique=True)),
                ('loan_account_number', models.CharField(blank=True, max_length=30, null=True, unique=True)),
                ('customer_first_name', models.CharField(max_length=100)),
                ('customer_last_name', models.CharField(max_length=100)),
                ('customer_phone', models.CharField(max_length=15)),
                ('customer_email', models.EmailField(blank=True, max_length=254)),
                ('customer_dob', models.DateField(blank=True, null=True)),
                ('customer_gender', models.CharField(blank=True, max_length=10)),
                ('aadhaar_number', models.CharField(blank=True, max_length=12)),
                ('pan_number', models.CharField(blank=True, max_length=10)),
                ('address_line1', models.CharField(blank=True, max_length=255)),
                ('address_line2', models.CharField(blank=True, max_length=255)),
                ('city', models.CharField(blank=True, max_length=100)),
                ('state', models.CharField(blank=True, max_length=100)),
                ('pincode', models.CharField(blank=True, max_length=10)),
                ('employment_type', models.CharField(blank=True, choices=[('salaried', 'Salaried'), ('self_employed', 'Self Employed'), ('business', 'Business Owner'), ('retired', 'Retired'), ('other', 'Other')], max_length=20)),
                ('employer_name', models.CharField(blank=True, max_length=200)),
                ('monthly_income', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('annual_income', models.DecimalField(decimal_places=2, default=0, max_digits=14)),
                ('loan_amount', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('loan_tenure_months', models.IntegerField(default=12)),
                ('interest_rate', models.DecimalField(decimal_places=2, default=0, max_digits=5)),
                ('loan_purpose', models.CharField(blank=True, max_length=255)),
                ('bank_account_number', models.CharField(blank=True, max_length=30)),
                ('bank_ifsc', models.CharField(blank=True, max_length=15)),
                ('bank_account_holder', models.CharField(blank=True, max_length=200)),
                ('bank_name', models.CharField(blank=True, max_length=200)),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('submitted', 'Submitted'), ('under_review', 'Under Review'), ('kyc_verified', 'KYC Verified'), ('credit_checked', 'Credit Checked'), ('approved', 'Approved'), ('rejected', 'Rejected'), ('disbursal_ready', 'Disbursal Ready'), ('disbursed', 'Disbursed')], default='draft', max_length=20)),
                ('rejection_reason', models.TextField(blank=True)),
                ('underwriting_notes', models.TextField(blank=True)),
                ('submitted_at', models.DateTimeField(blank=True, null=True)),
                ('approved_at', models.DateTimeField(blank=True, null=True)),
                ('rejected_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('agent', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='loan_applications', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
