# Generated by Django 6.0.2 on 2026-02-23 22:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('loans', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='loanapplication',
            name='employer_address',
            field=models.CharField(blank=True, max_length=500),
        ),
        migrations.AlterField(
            model_name='loanapplication',
            name='employment_type',
            field=models.CharField(blank=True, choices=[('salaried', 'Salaried'), ('self_employed', 'Self Employed'), ('business', 'Business Owner'), ('professional', 'Professional'), ('agriculture', 'Agriculture'), ('retired', 'Retired'), ('other', 'Other')], max_length=20),
        ),
    ]
